name: Moodle Plugin Release

on:
  workflow_call:
    inputs:
      tag:
        description: 'Git tag to be released. If not set, the tag is taken from the triggering event.'
        type: string
        required: false
      plugin-name:
        description: 'Deprecated and ignored. The plugin frankenstyle name is read from version.php by the Moodle HQ tool now.'
        type: string
        required: false
    secrets:
      MOODLE_ORG_TOKEN:
        description: 'Moodle Marketplace API token for plugin releases'
        required: true

jobs:
  release-to-marketplace:
    uses: moodlehq/moodle-plugin-release/.github/workflows/moodle-release.yml@main
    with:
      tag: ${{ inputs.tag || github.event.inputs.tag }}
    secrets:
      MOODLE_MARKETPLACE_TOKEN: ${{ secrets.MOODLE_ORG_TOKEN }}
